name: Prediccion_Diaria_Mundial
on:
  schedule:
    - cron: '0 8 * * *' # Se ejecuta todos los días a las 8:00 AM UTC
  workflow_dispatch: # Botón para ejecutar manual

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install pandas scikit-learn joblib requests tabulate

      - name: Ejecutar Predicciones
        run: python predict_daily.py

      - name: Guardar cambios en README
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Actualización diaria de predicciones" || exit 0
          git push
